server:
  name: "gin-demo"
  mode: "debug"
  host: localhost
  port: 8080
  relative_path: "/api"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "go-gin"
  max_idle_conns: 10
  max_open_conns: 50
  log_debug: true

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
